// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { useState, useCallback, useMemo, useEffect, useRef, useContext, useReducer } from 'react';
  export { fakeBrowser } from 'wxt/testing';
  export { ActionButton } from '../components/ActionButton';
  export { ActionMenu } from '../components/ActionMenu';
  export { BottomPlayerInfo } from '../components/BottomPlayerInfo';
  export { CheatSheet } from '../components/CheatSheet';
  export { ConfirmationDialog } from '../components/ConfirmationDialog';
  export { EmptyPlayerCard } from '../components/EmptyPlayerCard';
  export { ExchangeCardsDialog } from '../components/ExchangeCardsDialog';
  export { GameCreation } from '../components/GameCreation';
  export { GameLobby } from '../components/GameLobby';
  export { GameLog } from '../components/GameLog';
  export { GameOverScreen } from '../components/GameOverScreen';
  export { GameView } from '../components/GameView';
  export { InfluenceCards } from '../components/InfluenceCards';
  export { InvestigateDecisionDialog } from '../components/InvestigateDecisionDialog';
  export { LoseInfluenceDialog } from '../components/LoseInfluenceDialog';
  export { MainMenu } from '../components/MainMenu';
  export { PlayerCard } from '../components/PlayerCard';
  export { ResponseButtons } from '../components/ResponseButtons';
  export { SelectCardForInvestigationDialog } from '../components/SelectCardForInvestigationDialog';
  export { SignInButton } from '../components/SignInButton';
  export { TargetSelectionOverlay } from '../components/TargetSelectionOverlay';
  export { useAuth, AuthState } from '../hooks/useAuth';
  export { useGame } from '../hooks/useGame';
  export { useGameState } from '../hooks/useGameState';
  export { savePlayerName, getPlayerName, savePlayerId, getPlayerId, getUser, saveUser, clearUser, removePlayerName, User } from '../utils/storage';
}
